version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/aws-codedeploy
permissions:
  - object: /home/ec2-user
    owner: ec2-user
    group: ec2-user
    type:
      - directory
      - file
hooks:
  ApplicationStop:
    - location: scripts/stop-pm2.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/reload-pm2.sh
      timeout: 300
      runas: ec2-user
